spring:
  application:
    name: mvk-traders-api
  datasource:
    url: jdbc:mysql://localhost:3306/investment_analysis
    username: app_user
    password: "mSRINIVAS777!!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false

logging:
  level:
    com.enterprise.investmentanalytics: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  file:
    name: /var/log/mvk-traders/application.log

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-expiration: 604800000
