spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investment_analysis
    username: root
    password: "#JAYA1708!!"
    # username: app_user
    # password: "mSRINIVAS777!!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  
h2:
  console:
    enabled: true
    path: /h2-console

jwt:
  secret: verysecretkeythatshouldbechangedinproductionandmustbelongenoughforhs512
  expiration: 86400000
  refresh-expiration: 604800000
