spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investment_analysis
    username: root
    password: "#JAYA1708!!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
