spring:
  application:
    name: investment-analytics
  profiles:
    active: local # Default to local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.enterprise.investmentanalytics: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

server:
  port: 8080
  error:
    include-message: always

app:
  scheduling:
    profit-calculation-rate: 30000

jwt:
  secret: verysecretkeythatshouldbechangedinproductionandmustbelongenoughforhs512
  expiration: 86400000 
  refresh-expiration: 604800000 

aws:
  s3:
    bucket: mvktraders-assets
    region: eu-north-1
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
