spring:
  application:
    name: investment-analytics
  datasource:
    # url: jdbc:mysql://localhost:3306/investment_analysis
    # username: root
    # password: "#JAYA1708!!"
    url: jdbc:mysql://localhost:3306/investment_analysis
    username: app_user
    password: "mSRINIVAS777!!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false
  
logging:
  level:
    com.enterprise.investmentanalytics: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: verysecretkeythatshouldbechangedinproductionandmustbelongenoughforhs512
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days
